version: '3'

volumes:
  postgres:
  # redis:

services:
  php-fpm:
    container_name: dbf_php-fpm
    build: .docker/php-fpm
    volumes:
      - .:/var/www/app
    network_mode: bridge
    links:
      # - redis
      - postgres

  nginx:
    container_name: partners_nginx
    build: .docker/nginx
    volumes:
      - .:/var/www/app
    network_mode: bridge
    ports:
      - "${SERVER_PORT}:80"
    links:
      - php-fpm
      # - redis
      - postgres

  postgres:
    env_file:
      - .env
    container_name: ${DB_HOST}
    build: .docker/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    network_mode: bridge
    ports:
      - 5432:5432

  # redis:
  #   container_name: ${REDIS_HOST}
  #   build:
  #     context: .docker/redis
  #     args:
  #       - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   volumes:
  #     - redis:/data
  #   network_mode: bridge